<a href="https://colab.research.google.com/github/Shiladitya56/Machine-Learning/blob/main/test3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MARKET BASKET ANALYSIS**

In [78]:
import pandas as pd
import numpy as np
from numpy import nan
import matplotlib.pyplot as pt
import seaborn as sb
import warnings
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.frequent_patterns.fpgrowth import fpgrowth
warnings.filterwarnings('ignore', category=DeprecationWarning)
warnings.filterwarnings('ignore', category=FutureWarning)

In [57]:
df = pd.read_csv('/content/drive/MyDrive/ipynb/datasets/Market_Basket_Optimisation.csv')
df

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7496,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
df.dtypes

shrimp                object
almonds               object
avocado               object
vegetables mix        object
green grapes          object
whole weat flour      object
yams                  object
cottage cheese        object
energy drink          object
tomato juice          object
low fat yogurt        object
green tea             object
honey                 object
salad                 object
mineral water         object
salmon                object
antioxydant juice     object
frozen smoothie       object
spinach               object
olive oil            float64
dtype: object

In [59]:
df.shape[1]

20

In [60]:
df = df.astype('str')

In [61]:
#let us first get all the transactions
transactions = []
for i in range(7500):
  for j in range(20):
    if df.values[i,j]=='nan':
      transactions.append('0')
      break
    else:
      transactions.append(df.values[i,j])

In [62]:
sublist = []
trans = []
for x in transactions:
  if x == '0':
    trans.append(sublist)
    sublist = []
  else:
    sublist.append(x)
if sublist:
  trans.append(sublist)

In [63]:
len(trans)

7500

In [64]:
c = 0
for x in trans:
  if len(x) > c:
    c = len(x)
    p = x
print(p,'\n',c)

['fresh tuna', 'frozen vegetables', 'parmesan cheese', 'pepper', 'spaghetti', 'milk', 'olive oil', 'black tea', 'almonds', 'salmon', 'honey', 'cake', 'gums', 'oil', 'cereals', 'chocolate', 'frozen smoothie', 'protein bar', 'mayonnaise']
 19

In [65]:
flat = [x for _ in trans for x in _]
len(flat)

29343

In [66]:
items = list(set(x for _ in trans for x in _))
items.sort()
print(len(items))

120

In [67]:
mydf = pd.DataFrame(0, index=range(7500), columns = items)
mydf

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [68]:
c = -1
for x in trans:
  c+=1
  for y in x:
      mydf.at[c,y] = 1

In [69]:
mydf

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7495,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

**APRIORI**

In [70]:
frequent_itemset = apriori(mydf,min_support=0.01,use_colnames=True)
frequent_itemset

      support                                 itemsets
0    0.020267                                (almonds)
1    0.033200                                (avocado)
2    0.010800                         (barbecue sauce)
3    0.014267                              (black tea)
4    0.011467                             (body spray)
..        ...                                      ...
254  0.011067       (milk, mineral water, ground beef)
255  0.017067  (spaghetti, mineral water, ground beef)
256  0.015733         (milk, spaghetti, mineral water)
257  0.010267    (spaghetti, mineral water, olive oil)
258  0.011467     (pancakes, spaghetti, mineral water)

[259 rows x 2 columns]

In [71]:
rulea = association_rules(frequent_itemset,metric='lift',min_threshold=1)
rulea

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(avocado),(mineral water),0.033200,0.238267,0.011467,0.345382,1.449559,0.003556,1.163629,0.320785
1,(mineral water),(avocado),0.238267,0.033200,0.011467,0.048125,1.449559,0.003556,1.015680,0.407144
2,(cake),(burgers),0.081067,0.087200,0.011467,0.141447,1.622103,0.004398,1.063185,0.417349
3,(burgers),(cake),0.087200,0.081067,0.011467,0.131498,1.622103,0.004398,1.058068,0.420154
4,(burgers),(chocolate),0.087200,0.163867,0.017067,0.195719,1.194377,0.002777,1.039603,0.178291
...,...,...,...,...,...,...,...,...,...,...
403,"(pancakes, mineral water)",(spaghetti),0.033733,0.174133,0.011467,0.339921,1.952073,0.005593,1.251163,0.504751
404,"(spaghetti, mineral water)",(pancakes),0.059733,0.095067,0.011467,0.191964,2.019260,0.005788,1.119917,0.536836
405,(pancakes),"(spaghetti, mineral water)",0.095067,0.059733,0.011467,0.120617,2.019260,0.005788,1.069235,0.557797
406,(spaghetti),"(pancakes, mineral water)",0.174133,0.033733,0.011467,0.065850,1.952073,0.005593,1.034381,0.590560
407,(mineral water),"(pancakes, spaghetti)",0.238267,0.025200,0.011467,0.048125,1.909736,0.005462,1.024084,0.625373

**FP-GROWTH**

In [72]:
freq_itemset = fpgrowth(mydf, min_support=0.01, use_colnames=True)
freq_itemset

      support                               itemsets
0    0.179733                                 (eggs)
1    0.087200                              (burgers)
2    0.020933                            (meatballs)
3    0.062533                               (turkey)
4    0.033200                              (avocado)
..        ...                                    ...
254  0.014133               (ground beef, olive oil)
255  0.011333         (frozen vegetables, olive oil)
256  0.012000                      (eggs, olive oil)
257  0.010800                  (pancakes, olive oil)
258  0.010267  (spaghetti, mineral water, olive oil)

[259 rows x 2 columns]

In [73]:
rulep = association_rules(freq_itemset, metric='lift', min_threshold=0.5)
rulep

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(eggs),(mineral water),0.179733,0.238267,0.050933,0.283383,1.189351,0.008109,1.062957,0.194090
1,(mineral water),(eggs),0.238267,0.179733,0.050933,0.213766,1.189351,0.008109,1.043286,0.209004
2,(burgers),(eggs),0.087200,0.179733,0.028800,0.330275,1.837585,0.013127,1.224782,0.499351
3,(eggs),(burgers),0.179733,0.087200,0.028800,0.160237,1.837585,0.013127,1.086974,0.555682
4,(burgers),(mineral water),0.087200,0.238267,0.024400,0.279817,1.174384,0.003623,1.057693,0.162675
...,...,...,...,...,...,...,...,...,...,...
431,"(spaghetti, olive oil)",(mineral water),0.022933,0.238267,0.010267,0.447674,1.878880,0.004802,1.379138,0.478747
432,"(mineral water, olive oil)",(spaghetti),0.027467,0.174133,0.010267,0.373786,2.146553,0.005484,1.318826,0.549222
433,(spaghetti),"(mineral water, olive oil)",0.174133,0.027467,0.010267,0.058959,2.146553,0.005484,1.033465,0.646759
434,(mineral water),"(spaghetti, olive oil)",0.238267,0.022933,0.010267,0.043089,1.878880,0.004802,1.021063,0.614084
435,(olive oil),"(spaghetti, mineral water)",0.065733,0.059733,0.010267,0.156187,2.614731,0.006340,1.114306,0.661001

In [74]:
best_choices=rulea.sort_values(by='lift',ascending=False)
print('Best Choices are...')
print(best_choices[['antecedents','consequents','lift']])

Best Choices are...
                    antecedents                 consequents      lift
217               (ground beef)             (herb & pepper)  3.291555
216             (herb & pepper)               (ground beef)  3.291555
384  (spaghetti, mineral water)               (ground beef)  2.907540
389               (ground beef)  (spaghetti, mineral water)  2.907540
401                 (olive oil)  (spaghetti, mineral water)  2.614731
..                          ...                         ...       ...
155              (french fries)            (low fat yogurt)  1.020983
131                 (olive oil)                      (eggs)  1.015704
130                      (eggs)                 (olive oil)  1.015704
145                 (spaghetti)                  (escalope)  1.013422
144                  (escalope)                 (spaghetti)  1.013422

[408 rows x 3 columns]

In [77]:
print('Top 10 best choices are...')
print(best_choices[['antecedents', 'consequents']][:20:2])

Top 10 best choices are...
                      antecedents                         consequents
217                 (ground beef)                     (herb & pepper)
384    (spaghetti, mineral water)                       (ground beef)
401                   (olive oil)          (spaghetti, mineral water)
195                    (tomatoes)                 (frozen vegetables)
191                      (shrimp)                 (frozen vegetables)
367         (milk, mineral water)                 (frozen vegetables)
386  (mineral water, ground beef)                         (spaghetti)
369                        (milk)  (frozen vegetables, mineral water)
378         (milk, mineral water)                       (ground beef)
255                        (soup)                              (milk)